# Generated by Django 5.2.1 on 2025-06-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_seat_seat_type_alter_seat_seat_number'),
        ('movies', '0002_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.show'),
        ),
    ]
