# Generated by Django 5.2.1 on 2025-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
