# Generated by Django 5.2.1 on 2025-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_price_booking_seat_number_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
