# Generated by Django 5.2.1 on 2025-06-03 03:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_show'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_indenstive_unique', violation_error_message='genre alredy exist'),
        ),
    ]
